spring:
  application:
    name: test-client
server:
  port: 8080

payments:
  base-url: http://localhost:8071
  checkout-url: http://localhost:8071
  connect-timeout: 3s
  read-timeout: 10s
  sse:
    reconnect-delay: 2s

merchant:
  client-id: 00000000-0000-0000-0000-000000000001
  client-name: 테스트 클라이언트
  api-key: 00000000-0000-0000-0000-000000000002

logging:
  config: classpath:log4j2-spring.xml

management:
  zipkin:
    tracing:
      export:
        enabled: false
  tracing:
    sampling:
      probability: 1
