services:
  mysql:
    image: mysql:8.0
    networks:
      - haru_network
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./infrastructure/volumes/mysql:/var/lib/mysql
  connect:
    image: quay.io/debezium/connect
    links:
      - kafka-1:kafka-1
      - kafka-2:kafka-2
      - kafka-3:kafka-3
      - mysql:mysql
    ports:
      - "8075:8083"
    environment:
      - BOOTSTRAP_SERVERS=kafka-1:29092,kafka-2:29092,kafka-3:29092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    networks:
      - haru_network
  kafka-1:
    container_name: kafka-1
    image: confluentinc/cp-kafka:7.9.0
    ports:
      - "9092:9092"
    volumes:
      - ./infrastructure/volumes/kafka/kafka-1:/var/lib/kafka/data
    networks:
      - haru_network
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:29092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENERS: INTERNAL://:29092,CONTROLLER://:29094,EXTERNAL://0.0.0.0:9092
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:29094,2@kafka-2:29094,3@kafka-3:29094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      CLUSTER_ID: ${KAFKA_CLUSTER_ID:-MkU3OEVBNTcwNTJENDM2Qk}
  kafka-2:
    container_name: kafka-2
    image: confluentinc/cp-kafka:7.9.0
    ports:
      - "9095:9095"
    volumes:
      - ./infrastructure/volumes/kafka/kafka-2:/var/lib/kafka/data
    networks:
      - haru_network
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:29092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9095
      KAFKA_LISTENERS: INTERNAL://:29092,CONTROLLER://:29094,EXTERNAL://0.0.0.0:9095
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:29094,2@kafka-2:29094,3@kafka-3:29094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      CLUSTER_ID: ${KAFKA_CLUSTER_ID:-MkU3OEVBNTcwNTJENDM2Qk}
  kafka-3:
    container_name: kafka-3
    image: confluentinc/cp-kafka:7.9.0
    ports:
      - "9096:9096"
    volumes:
      - ./infrastructure/volumes/kafka/kafka-3:/var/lib/kafka/data
    networks:
      - haru_network
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:29092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9096
      KAFKA_LISTENERS: INTERNAL://:29092,CONTROLLER://:29094,EXTERNAL://0.0.0.0:9096
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:29094,2@kafka-2:29094,3@kafka-3:29094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      CLUSTER_ID: ${KAFKA_CLUSTER_ID:-MkU3OEVBNTcwNTJENDM2Qk}
  kafka-ui:
    image: provectuslabs/kafka-ui
    networks:
      - haru_network
    ports:
      - "8989:8080"
    restart: always
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:29092,kafka-2:29092,kafka-3:29092
  auth:
    image: haru-auth:0.0.1-SNAPSHOT
    networks:
      - haru_network
    ports:
      - "8072:8072"
    depends_on:
      - mysql
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
  payments:
    image: haru-payments:0.0.1-SNAPSHOT
    networks:
      - haru_network
    ports:
      - "8071:8071"
    depends_on:
      - mysql
      - kafka-1
      - kafka-2
      - kafka-3
      - auth
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
  money:
    image: haru-money:0.0.1-SNAPSHOT
    networks:
      - haru_network
    ports:
      - "8073:8073"
    depends_on:
      - mysql
      - kafka-1
      - kafka-2
      - kafka-3
      - auth
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
  orchestrator:
    image: haru-orchestrator:0.0.1-SNAPSHOT
    networks:
      - haru_network
    ports:
      - "8077:8077"
    depends_on:
      - mysql
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
  user-api:
    image: haru-user-api:0.0.1-SNAPSHOT
    networks:
      - haru_network
    ports:
      - "8070:8070"
    depends_on:
      - mysql
      - auth
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
  banking:
    image: haru-banking:0.0.1-SNAPSHOT
    networks:
      - haru_network
    ports:
      - "8074:8074"
    depends_on:
      - mysql
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
  setup:
    profiles:
      - setup
    build:
      context: infrastructure/setup/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    init: true
    volumes:
      - ./infrastructure/setup/entrypoint.sh:/entrypoint.sh:ro,Z
      - ./infrastructure/setup/lib.sh:/lib.sh:ro,Z
      - ./infrastructure/setup/roles:/roles:ro,Z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
      METRICBEAT_INTERNAL_PASSWORD: ${METRICBEAT_INTERNAL_PASSWORD:-}
      HEARTBEAT_INTERNAL_PASSWORD: ${HEARTBEAT_INTERNAL_PASSWORD:-}
      MONITORING_INTERNAL_PASSWORD: ${MONITORING_INTERNAL_PASSWORD:-}
      BEATS_SYSTEM_PASSWORD: ${BEATS_SYSTEM_PASSWORD:-}
    networks:
      - haru_network
    depends_on:
      - elasticsearch
  elasticsearch:
    build:
      context: infrastructure/elasticsearch/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./infrastructure/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - elasticsearch:/usr/share/elasticsearch/data:Z
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      discovery.type: single-node
    networks:
      - haru_network
    restart: unless-stopped
  logstash:
    build:
      context: infrastructure/logstash/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./infrastructure/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./infrastructure/logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    ports:
      - 5044:5044
      - 50000:50000/tcp
      - 50000:50000/udp
      - 9600:9600
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
    networks:
      - haru_network
    depends_on:
      - elasticsearch
      - kafka-1
      - kafka-2
      - kafka-3
    restart: unless-stopped
  kibana:
    build:
      context: infrastructure/kibana/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./infrastructure/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - 5601:5601
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    networks:
      - haru_network
    depends_on:
      - elasticsearch
    restart: unless-stopped

  redis-node-0: &redis-node
    networks:
      - haru_network
    image: docker.io/bitnami/redis-cluster:7.2
    ports:
      - 6479:6479
      - 16479:16479
    volumes:
      - ./infrastructure/volumes/redis/redis-cluster_data-0:/bitnami/redis/data
      - ./infrastructure/redis/overrides.conf:/opt/bitnami/redis/mounted-etc/overrides.conf:ro
    environment: &redis-env
      - 'REDIS_PORT_NUMBER=6479'
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0:6479 redis-node-1:6480 redis-node-2:6481 redis-node-3:6482 redis-node-4:6483 redis-node-5:6484'
    healthcheck: &redis-healthcheck
      test: ["CMD", "redis-cli", "-p", "6479", "-a", "bitnami", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis-node-1:
    <<: *redis-node
    ports:
      - 6480:6480
      - 16480:16480
    volumes:
      - ./infrastructure/volumes/redis/redis-cluster_data-1:/bitnami/redis/data
      - ./infrastructure/redis/overrides.conf:/opt/bitnami/redis/mounted-etc/overrides.conf:ro
    environment:
      - 'REDIS_PORT_NUMBER=6480'
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0:6479 redis-node-1:6480 redis-node-2:6481 redis-node-3:6482 redis-node-4:6483 redis-node-5:6484'
    healthcheck:
      <<: *redis-healthcheck
      test: ["CMD", "redis-cli", "-p", "6480", "-a", "bitnami", "ping"]

  redis-node-2:
    <<: *redis-node
    ports:
      - 6481:6481
      - 16481:16481
    volumes:
      - ./infrastructure/volumes/redis/redis-cluster_data-2:/bitnami/redis/data
      - ./infrastructure/redis/overrides.conf:/opt/bitnami/redis/mounted-etc/overrides.conf:ro
    environment:
      - 'REDIS_PORT_NUMBER=6481'
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0:6479 redis-node-1:6480 redis-node-2:6481 redis-node-3:6482 redis-node-4:6483 redis-node-5:6484'
    healthcheck:
      <<: *redis-healthcheck
      test: ["CMD", "redis-cli", "-p", "6481", "-a", "bitnami", "ping"]

  redis-node-3:
    <<: *redis-node
    ports:
      - 6482:6482
      - 16482:16482
    volumes:
      - ./infrastructure/volumes/redis/redis-cluster_data-3:/bitnami/redis/data
      - ./infrastructure/redis/overrides.conf:/opt/bitnami/redis/mounted-etc/overrides.conf:ro
    environment:
      - 'REDIS_PORT_NUMBER=6482'
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0:6479 redis-node-1:6480 redis-node-2:6481 redis-node-3:6482 redis-node-4:6483 redis-node-5:6484'
    healthcheck:
      <<: *redis-healthcheck
      test: ["CMD", "redis-cli", "-p", "6482", "-a", "bitnami", "ping"]

  redis-node-4:
    <<: *redis-node
    ports:
      - 6483:6483
      - 16483:16483
    volumes:
      - ./infrastructure/volumes/redis/redis-cluster_data-4:/bitnami/redis/data
      - ./infrastructure/redis/overrides.conf:/opt/bitnami/redis/mounted-etc/overrides.conf:ro
    environment:
      - 'REDIS_PORT_NUMBER=6483'
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0:6479 redis-node-1:6480 redis-node-2:6481 redis-node-3:6482 redis-node-4:6483 redis-node-5:6484'
    healthcheck:
      <<: *redis-healthcheck
      test: ["CMD", "redis-cli", "-p", "6483", "-a", "bitnami", "ping"]

  redis-node-5:
    <<: *redis-node
    ports:
      - 6484:6484
      - 16484:16484
    volumes:
      - ./infrastructure/volumes/redis/redis-cluster_data-5:/bitnami/redis/data
      - ./infrastructure/redis/overrides.conf:/opt/bitnami/redis/mounted-etc/overrides.conf:ro
    environment:
      - 'REDIS_PORT_NUMBER=6484'
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0:6479 redis-node-1:6480 redis-node-2:6481 redis-node-3:6482 redis-node-4:6483 redis-node-5:6484'
    healthcheck:
      <<: *redis-healthcheck
      test: ["CMD", "redis-cli", "-p", "6484", "-a", "bitnami", "ping"]
  # Test Client
  test-client:
    image: haru-test-client:0.0.1-SNAPSHOT
    networks:
      - haru_network
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
      - PAYMENTS_BASE_URL=http://payments:8071
    depends_on:
      - payments
networks:
  haru_network:
    driver: bridge

volumes:
  elasticsearch:
