spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://mysql:3306/auth
    password: password
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth:8072
client:
  user:
    url: http://user-api:8070
server:
  port: 8072
logging:
  config: classpath:log4j2-spring-docker.xml
management:
  zipkin:
    tracing:
      export:
        enabled: false
  tracing:
    sampling:
      probability: 1