#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOG_DIR="$ROOT_DIR/.dev/logs"

MODULES=(auth user-api payments money banking orchestrator test-client)
REDIS_NODES=(redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5)
REDIS_INTERNAL_PORT=6379
REDIS_EXTERNAL_PORTS=(6479 6480 6481 6482 6483 6484)
REDIS_PASSWORD=bitnami
INFRA_SERVICES=(
  mysql
  kafka-1 kafka-2 kafka-3
  "${REDIS_NODES[@]}"
  connect
  kafka-ui
  elasticsearch logstash kibana
)

mkdir -p "$LOG_DIR"

usage() {
  cat <<USAGE
Usage:
  scripts/devctl.sh infra up|down|status|logs [service]
  scripts/devctl.sh module start|stop|restart|status|logs <module|all>
  scripts/devctl.sh redis up|down|init|sessions|flush-sessions

Modules:
  ${MODULES[*]}

Examples:
  scripts/devctl.sh infra up
  scripts/devctl.sh module start payments
  scripts/devctl.sh module restart auth
  scripts/devctl.sh module logs test-client
  scripts/devctl.sh redis up
  scripts/devctl.sh redis init
  scripts/devctl.sh redis down
  scripts/devctl.sh redis sessions [key]
  scripts/devctl.sh redis flush-sessions
USAGE
}

has_module() {
  local target="$1"
  for m in "${MODULES[@]}"; do
    if [[ "$m" == "$target" ]]; then
      return 0
    fi
  done
  return 1
}

log_file() {
  echo "$LOG_DIR/$1.log"
}

find_module_pids() {
  pgrep -f ":${1}:bootRun" 2>/dev/null
}

is_running() {
  pgrep -qf ":${1}:bootRun" 2>/dev/null
}

start_one_module() {
  local module="$1"
  if is_running "$module"; then
    echo "[module:$module] already running (pid $(find_module_pids "$module" | head -1))"
    return 0
  fi

  local log
  log="$(log_file "$module")"
  echo "[module:$module] starting..."
  nohup bash -lc "cd '$ROOT_DIR' && ./gradlew ':$module:bootRun' --console=plain" >"$log" 2>&1 &
  sleep 1
  if is_running "$module"; then
    echo "[module:$module] started (pid $(find_module_pids "$module" | head -1))"
    echo "[module:$module] log: $log"
  else
    echo "[module:$module] failed to start. check log: $log"
    return 1
  fi
}

stop_one_module() {
  local module="$1"
  if ! is_running "$module"; then
    echo "[module:$module] not running"
    return 0
  fi
  echo "[module:$module] stopping (pids: $(find_module_pids "$module" | tr '\n' ' '))..."
  pkill -f ":${module}:bootRun" 2>/dev/null || true
  for _ in {1..20}; do
    if ! is_running "$module"; then
      echo "[module:$module] stopped"
      return 0
    fi
    sleep 0.3
  done
  pkill -9 -f ":${module}:bootRun" 2>/dev/null || true
  echo "[module:$module] killed"
}

status_one_module() {
  local module="$1"
  if is_running "$module"; then
    echo "[module:$module] running (pids: $(find_module_pids "$module" | tr '\n' ' '))"
  else
    echo "[module:$module] stopped"
  fi
}

logs_one_module() {
  local module="$1"
  local log
  log="$(log_file "$module")"
  if [[ ! -f "$log" ]]; then
    echo "[module:$module] no log file yet"
    return 0
  fi
  tail -n 200 "$log"
}

generate_redis_overrides() {
  local announce_host="${REDIS_ANNOUNCE_HOST:-localhost}"
  local conf_file="$ROOT_DIR/infrastructure/redis/overrides.conf"

  mkdir -p "$(dirname "$conf_file")"
  cat > "$conf_file" <<EOF
# Auto-generated by devctl.sh — do not edit manually
cluster-announce-hostname ${announce_host}
cluster-preferred-endpoint-type hostname
EOF
  echo "[redis] cluster-announce-hostname: ${announce_host}"
}

wait_for_redis_nodes() {
  echo "[redis] waiting for all nodes to be healthy..."
  local max_wait=60
  local elapsed=0
  while (( elapsed < max_wait )); do
    local all_healthy=true
    for node in "${REDIS_NODES[@]}"; do
      if ! docker compose exec -T "$node" redis-cli -p "$REDIS_INTERNAL_PORT" -a "$REDIS_PASSWORD" ping 2>/dev/null | grep -q PONG; then
        all_healthy=false
        break
      fi
    done
    if $all_healthy; then
      echo "[redis] all nodes are ready"
      return 0
    fi
    sleep 2
    elapsed=$((elapsed + 2))
  done
  echo "[redis] WARNING: timed out waiting for nodes (${max_wait}s)"
  return 1
}

init_redis_cluster() {
  local cluster_state
  cluster_state="$(docker compose exec -T "${REDIS_NODES[0]}" \
    redis-cli -p "$REDIS_INTERNAL_PORT" -a "$REDIS_PASSWORD" cluster info 2>/dev/null | grep cluster_state)"

  if echo "$cluster_state" | grep -q "ok"; then
    echo "[redis] cluster already initialized — skipping"
    return 0
  fi

  echo "[redis] initializing cluster..."
  local node_addrs=""
  for node in "${REDIS_NODES[@]}"; do
    node_addrs+="${node}:${REDIS_INTERNAL_PORT} "
  done

  docker compose exec -T "${REDIS_NODES[0]}" \
    redis-cli -a "$REDIS_PASSWORD" --cluster create $node_addrs --cluster-replicas 1 --cluster-yes

  echo "[redis] cluster initialized"
}

redis_sessions() {
  local session_id="${1:-}"

  if [[ -n "$session_id" ]]; then
    echo "[redis] session: $session_id"
    redis-cli -c -p "${REDIS_EXTERNAL_PORTS[0]}" -a "$REDIS_PASSWORD" --no-auth-warning \
      HGETALL "$session_id" 2>/dev/null
    return 0
  fi

  echo "[redis] scanning all nodes for session keys..."
  local keys
  keys="$(
    for i in "${!REDIS_NODES[@]}"; do
      redis-cli -p "${REDIS_EXTERNAL_PORTS[$i]}" -a "$REDIS_PASSWORD" --no-auth-warning \
        --scan --pattern "payments:session*" 2>/dev/null
    done | sort -u
  )"

  if [[ -z "$keys" ]]; then
    echo "[redis] no active sessions"
    return 0
  fi

  echo ""
  while IFS= read -r key; do
    echo "  $key"
  done <<< "$keys"
}

redis_flush_sessions() {
  echo "[redis] scanning all nodes for session keys..."
  local keys
  keys="$(
    for i in "${!REDIS_NODES[@]}"; do
      redis-cli -p "${REDIS_EXTERNAL_PORTS[$i]}" -a "$REDIS_PASSWORD" --no-auth-warning \
        --scan --pattern "*:session*" 2>/dev/null
    done | sort -u
  )"

  if [[ -z "$keys" ]]; then
    echo "[redis] no session keys found"
    return 0
  fi

  local count
  count="$(echo "$keys" | wc -l | tr -d ' ')"
  echo "[redis] deleting ${count} session key(s)..."

  while IFS= read -r key; do
    redis-cli -c -p "${REDIS_EXTERNAL_PORTS[0]}" -a "$REDIS_PASSWORD" --no-auth-warning \
      DEL "$key" > /dev/null 2>&1
    echo "  deleted: $key"
  done <<< "$keys"

  echo "[redis] done"
}

redis_up() {
  (cd "$ROOT_DIR" && docker compose up -d "${REDIS_NODES[@]}")
}

redis_init() {
  wait_for_redis_nodes && init_redis_cluster
}

redis_down() {
  echo "[redis] stopping redis cluster..."
  (cd "$ROOT_DIR" && docker compose stop "${REDIS_NODES[@]}")
  echo "[redis] stopped"
}

run_redis_action() {
  local action="${1:-}"
  local arg="${2:-}"
  case "$action" in
    up)       redis_up ;;
    down)     redis_down ;;
    init)     redis_init ;;
    sessions)        redis_sessions "$arg" ;;
    flush-sessions)  redis_flush_sessions ;;
    *) echo "unknown redis action: $action"; usage; exit 1 ;;
  esac
}

infra_up() {
  echo "[infra] starting infrastructure services..."
  generate_redis_overrides
  (cd "$ROOT_DIR" && docker compose up -d "${INFRA_SERVICES[@]}")
  wait_for_redis_nodes && init_redis_cluster
  echo "[infra] started"
}

infra_down() {
  echo "[infra] stopping infrastructure services..."
  (cd "$ROOT_DIR" && docker compose stop "${INFRA_SERVICES[@]}")
  echo "[infra] stopped"
}

infra_status() {
  (cd "$ROOT_DIR" && docker compose ps "${INFRA_SERVICES[@]}")
}

infra_logs() {
  local service="${1:-}"
  if [[ -n "$service" ]]; then
    (cd "$ROOT_DIR" && docker compose logs --tail=200 "$service")
  else
    (cd "$ROOT_DIR" && docker compose logs --tail=200 "${INFRA_SERVICES[@]}")
  fi
}

run_module_action() {
  local action="$1"
  local target="$2"

  local selected=()
  if [[ "$target" == "all" ]]; then
    selected=("${MODULES[@]}")
  else
    if ! has_module "$target"; then
      echo "unknown module: $target"
      exit 1
    fi
    selected=("$target")
  fi

  for module in "${selected[@]}"; do
    case "$action" in
      start) start_one_module "$module" ;;
      stop) stop_one_module "$module" ;;
      restart) stop_one_module "$module"; start_one_module "$module" ;;
      status) status_one_module "$module" ;;
      logs) logs_one_module "$module" ;;
      *) echo "unknown module action: $action"; usage; exit 1 ;;
    esac
  done
}

if [[ $# -lt 2 ]]; then
  usage
  exit 1
fi

scope="$1"
action="$2"

case "$scope" in
  infra)
    case "$action" in
      up) infra_up ;;
      down) infra_down ;;
      status) infra_status ;;
      logs) infra_logs "${3:-}" ;;
      *) echo "unknown infra action: $action"; usage; exit 1 ;;
    esac
    ;;
  module)
    if [[ $# -lt 3 ]]; then
      echo "module target is required"
      usage
      exit 1
    fi
    run_module_action "$action" "$3"
    ;;
  redis)
    run_redis_action "$action" "${3:-}" "${4:-}"
    ;;
  *)
    echo "unknown scope: $scope"
    usage
    exit 1
    ;;
esac
