spring:
  application:
    name: joy-orchestrator
  datasource:
    url: jdbc:mysql://localhost:3308/joy
    password: password
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    client-id: joy-orchestrator
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true
      group-id: joy-orchestrator
    listener:
      concurrency: 2
      missing-topics-fatal: true
server:
  port: 8077
kafka:
  topic:
    saga:
      load-money-request:
        inbox:
          events: LoadMoneyRequestEvent.inbox.events
      load-money:
        inbox:
          events: LoadMoneyRequestCreatedEvent.inbox.events
      check-bank-account:
        inbox:
          events: CheckedRegisteredBankAccountEvent.inbox.events
      firm-banking:
        inbox:
          events: RequestFirmBankingFinishedEvent.inbox.events
      load-money-finish:
        inbox:
          events: LoadMoneyFinishedEvent.inbox.events
      payment-request:
        inbox:
          events: PaymentRequestEvent.inbox.events
      payment-request-created:
        inbox:
          events: PaymentRequestCreatedEvent.inbox.events
      decreased-money:
        inbox:
          events: DecreasedMoneyEvent.inbox.events
      payment-confirmed:
        inbox:
          events: PaymentConfirmedEvent.inbox.events