input {
    kafka {
        bootstrap_servers => "kafka-1:29092,kafka-2:29092,kafka-3:29092"
        topics => ["logs"]
        group_id => "logstash-consumer"
        codec => "json"
        auto_offset_reset => "latest"
    }
}

filter {
    date {
        match => ["timestamp", "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"]
        target => "@timestamp"
        remove_field => ["timestamp"]
    }
    mutate {
        remove_field => ["@version", "event"]
    }
}

output {
    elasticsearch {
        index => "%{[appName]}-logs-%{+yyyy.MM.dd}"
        hosts => "elasticsearch:9200"
        user => "logstash_internal"
        password => "${LOGSTASH_INTERNAL_PASSWORD}"
    }
}